### ISSUE TITLE
EdgeCast support?

### ISSUE THREAD

**Issue by jeisen** [VerizonDigital/terraform-provider-vmp#8]
It's difficult to tell -- does this provider also handle EdgeCast resources? I'm interested in using it to manage origin configs. I'm used to only needing the API key and account ID, whereas this provider asks for a client ID, partner ID and API URL.

**Comment by ramiroching** [comment]
@jeisen Thank you for the feedback. Yes, this provider does handle EdgeCast resources, to move forward we will ensure PartnerId, Partner UserId, and all 3 id_* settings to be optional, as well as the API URL(since it is intended for testing purpose.).  These changes will be updated by end of day tomorrow. 

We appreciate your patience. 

Ramiro

**Comment by stevenpaz** [comment]
@jeisen My apologies for the delay. We have released a new version (v0.0.7) that should make it easier to use the provider, but it has not yet propagated to the Terraform Registry. We have opened a ticket with Hashicorp and will follow up with you when this is resolved.

**Comment by stevenpaz** [comment]
@jeisen please use v0.0.8 in your Terraform configuration - we have reduced the required parameters down to just your API Token and the rest are now optional.
